# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cci502/software/box2d-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cci502/software/box2d-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/cci502/software/box2d-master && $(CMAKE_COMMAND) -E cmake_progress_start /home/cci502/software/box2d-master/CMakeFiles /home/cci502/software/box2d-master/colregs_sim//CMakeFiles/progress.marks
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colregs_sim/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cci502/software/box2d-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colregs_sim/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colregs_sim/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colregs_sim/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/cci502/software/box2d-master && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
colregs_sim/CMakeFiles/mass_colregs.dir/rule:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colregs_sim/CMakeFiles/mass_colregs.dir/rule
.PHONY : colregs_sim/CMakeFiles/mass_colregs.dir/rule

# Convenience name for target.
mass_colregs: colregs_sim/CMakeFiles/mass_colregs.dir/rule
.PHONY : mass_colregs

# fast build rule for target.
mass_colregs/fast:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/build
.PHONY : mass_colregs/fast

src/agent.o: src/agent.cpp.o
.PHONY : src/agent.o

# target to build an object file
src/agent.cpp.o:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/agent.cpp.o
.PHONY : src/agent.cpp.o

src/agent.i: src/agent.cpp.i
.PHONY : src/agent.i

# target to preprocess a source file
src/agent.cpp.i:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/agent.cpp.i
.PHONY : src/agent.cpp.i

src/agent.s: src/agent.cpp.s
.PHONY : src/agent.s

# target to generate assembly for a file
src/agent.cpp.s:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/agent.cpp.s
.PHONY : src/agent.cpp.s

src/genetic_algorithm.o: src/genetic_algorithm.cpp.o
.PHONY : src/genetic_algorithm.o

# target to build an object file
src/genetic_algorithm.cpp.o:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/genetic_algorithm.cpp.o
.PHONY : src/genetic_algorithm.cpp.o

src/genetic_algorithm.i: src/genetic_algorithm.cpp.i
.PHONY : src/genetic_algorithm.i

# target to preprocess a source file
src/genetic_algorithm.cpp.i:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/genetic_algorithm.cpp.i
.PHONY : src/genetic_algorithm.cpp.i

src/genetic_algorithm.s: src/genetic_algorithm.cpp.s
.PHONY : src/genetic_algorithm.s

# target to generate assembly for a file
src/genetic_algorithm.cpp.s:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/genetic_algorithm.cpp.s
.PHONY : src/genetic_algorithm.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mass_agent.o: src/mass_agent.cpp.o
.PHONY : src/mass_agent.o

# target to build an object file
src/mass_agent.cpp.o:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/mass_agent.cpp.o
.PHONY : src/mass_agent.cpp.o

src/mass_agent.i: src/mass_agent.cpp.i
.PHONY : src/mass_agent.i

# target to preprocess a source file
src/mass_agent.cpp.i:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/mass_agent.cpp.i
.PHONY : src/mass_agent.cpp.i

src/mass_agent.s: src/mass_agent.cpp.s
.PHONY : src/mass_agent.s

# target to generate assembly for a file
src/mass_agent.cpp.s:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/mass_agent.cpp.s
.PHONY : src/mass_agent.cpp.s

src/normal_agent.o: src/normal_agent.cpp.o
.PHONY : src/normal_agent.o

# target to build an object file
src/normal_agent.cpp.o:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/normal_agent.cpp.o
.PHONY : src/normal_agent.cpp.o

src/normal_agent.i: src/normal_agent.cpp.i
.PHONY : src/normal_agent.i

# target to preprocess a source file
src/normal_agent.cpp.i:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/normal_agent.cpp.i
.PHONY : src/normal_agent.cpp.i

src/normal_agent.s: src/normal_agent.cpp.s
.PHONY : src/normal_agent.s

# target to generate assembly for a file
src/normal_agent.cpp.s:
	cd /home/cci502/software/box2d-master && $(MAKE) $(MAKESILENT) -f colregs_sim/CMakeFiles/mass_colregs.dir/build.make colregs_sim/CMakeFiles/mass_colregs.dir/src/normal_agent.cpp.s
.PHONY : src/normal_agent.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mass_colregs"
	@echo "... src/agent.o"
	@echo "... src/agent.i"
	@echo "... src/agent.s"
	@echo "... src/genetic_algorithm.o"
	@echo "... src/genetic_algorithm.i"
	@echo "... src/genetic_algorithm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mass_agent.o"
	@echo "... src/mass_agent.i"
	@echo "... src/mass_agent.s"
	@echo "... src/normal_agent.o"
	@echo "... src/normal_agent.i"
	@echo "... src/normal_agent.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/cci502/software/box2d-master && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

